Repository Seagate/cortx-s3server, pull requests merged in 2021-09, with the labels that each got.

#1221 Addition of Multipart testcases.
  scripts/compatibility-test/ceph/s3_v2_tests.txt
  scripts/compatibility-test/ceph/s3_v4_tests.txt
  scripts/compatibility-test/splunk/s3_v2_tests.txt
  scripts/compatibility-test/splunk/s3_v4_tests.txt
Labels: cla-signed

#1206 EOS-23476 [F-99A] k8s ENABLER: s3server: Remove Systemd dependency an…
  system/s3server@.service
  system/s3startsystem.sh
Labels: cla-signed

#1226 Update CORTX-S3 Server Quick Start Guide.md
  docs/CORTX-S3 Server Quick Start Guide.md
Labels: cla-signed

#1227 [EOS-23396] Changes for seperation of endpoint configuration.
  s3backgrounddelete/s3backgrounddelete/config/s3_background_delete_config.yaml.sample
  s3backgrounddelete/s3backgrounddelete/cortx_s3_client.py
  s3backgrounddelete/s3backgrounddelete/cortx_s3_config.py
  s3backgrounddelete/s3backgrounddelete/cortx_s3_constants.py
  s3backgrounddelete/s3backgrounddelete/cortx_s3_count_kv.py
  s3backgrounddelete/s3backgrounddelete/cortx_s3_index_api.py
  s3backgrounddelete/s3backgrounddelete/cortx_s3_kv_api.py
  s3backgrounddelete/s3backgrounddelete/cortx_s3_object_api.py
  s3backgrounddelete/s3backgrounddelete/cortx_s3_util.py
  s3backgrounddelete/s3backgrounddelete/object_recovery_msgbus.py
  s3backgrounddelete/s3backgrounddelete/object_recovery_scheduler.py
  s3backgrounddelete/s3backgrounddelete/object_recovery_validator.py
  s3backgrounddelete/scripts/delete_kv.py
  s3backgrounddelete/scripts/get_kv.py
  s3backgrounddelete/scripts/list_kv.py
  s3backgrounddelete/scripts/put_kv.py
  s3backgrounddelete/tests/create_probable_delete_oid.py
  s3backgrounddelete/ut/cortx_s3_client_tests.py
  s3backgrounddelete/ut/cortx_s3_config_tests.py
  s3backgrounddelete/ut/cortx_s3_index_api_tests.py
  s3backgrounddelete/ut/cortx_s3_kv_api_tests.py
  s3backgrounddelete/ut/cortx_s3_object_api_tests.py
  scripts/ldap/create_account_using_cipher.py
  scripts/reset/precheck.py
  st/clitests/backgrounddelete_spec.py
  st/clitests/s3_background_delete_config_test.yaml
Labels: cla-signed

#1225 EOS-22437: Handling Overwrite case for Multipart new design
  server/s3_object_metadata.cc
  server/s3_post_complete_action.h
  server/s3_put_object_action.cc
  server/s3_put_object_action.h
Labels: cla-signed

#1232 Multipart Logger Changes
  s3backgrounddelete/s3backgrounddelete/object_recovery_validator.py
Labels: cla-signed

#1230 EOS-24033: Optional/Mandatory parameter separation
  scripts/provisioning/configcmd.py
  scripts/provisioning/s3_prov_config.yaml
  scripts/provisioning/setupcmd.py
Labels: cla-signed

#1229 EOS-23481 k8s ENABLER: BG Producer: Remove Systemd dependency and add…
  installhelper.sh
  rpms/s3/s3rpm.spec
  scripts/provisioning/s3_start
  starts3backgroundconsumer.sh
  starts3backgroundproducer.sh
Labels: cla-signed

#1231 EOS-22342 : Adding haproxy service handler
  scripts/provisioning/s3_start
Labels: cla-signed

#1236 [EOS-24033] : Commenting params to test changes done to EOS-24033.
  scripts/provisioning/s3_prov_config.yaml
  scripts/provisioning/templates/s3.config.tmpl.1-node
  scripts/provisioning/templates/s3.config.tmpl.1-node.sample
  scripts/provisioning/templates/s3.config.tmpl.3-node
  scripts/provisioning/templates/s3.config.tmpl.3-node.sample
  scripts/provisioning/templates/s3.init.tmpl.1-node
  scripts/provisioning/templates/s3.init.tmpl.1-node.sample
  scripts/provisioning/templates/s3.post_install.tmpl.1-node
  scripts/provisioning/templates/s3.post_install.tmpl.1-node.sample
  scripts/provisioning/templates/s3.prepare.tmpl.1-node
  scripts/provisioning/templates/s3.prepare.tmpl.1-node.sample
  scripts/provisioning/templates/s3.test.tmpl.1-node
  scripts/provisioning/templates/s3.test.tmpl.1-node.sample
Labels: cla-signed

#1239 [K8S] Code check format fix on K8S branch
  auth/server/src/test/java/com/seagates3/authserver/AuthServerConfigTest.java
  auth/server/src/test/java/com/seagates3/perf/S3PerfTest.java
Labels: cla-signed

#1102 EOS-23396: [K8S] Config file changes
  auth/server/s3authserver.service
  auth/server/src/main/java/com/seagates3/authserver/AuthServer.java
  auth/server/src/main/java/com/seagates3/authserver/AuthServerConfig.java
  auth/server/src/main/java/com/seagates3/authserver/AuthServerConstants.java
  auth/server/src/test/java/com/seagates3/authserver/AuthServerConfigTest.java
  jenkins-build.sh
  s3backgrounddelete/s3backgrounddelete/cortx_cluster_config.py
  s3backgrounddelete/s3backgrounddelete/cortx_s3_config.py
  s3config-test.yaml
  s3config.release.yaml.sample
  s3config.yaml.sample
  scripts/create_auth_jks_password.sh
  scripts/enc_ldap_passwd_in_cfg.sh
  scripts/ldap/setup_ldap.sh
  scripts/provisioning/cleanupcmd.py
  scripts/provisioning/configcmd.py
  scripts/provisioning/initcmd.py
  scripts/provisioning/postinstallcmd.py
  scripts/provisioning/postupgradecmd.py
  scripts/provisioning/preparecmd.py
  scripts/provisioning/preupgradecmd.py
  scripts/provisioning/s3_haproxy_config.py
  scripts/provisioning/s3_prov_config.yaml
  scripts/provisioning/s3setup_prereqs.json
  scripts/provisioning/setupcmd.py
  scripts/provisioning/templates/s3.cleanup.tmpl.1-node
  scripts/provisioning/templates/s3.cleanup.tmpl.1-node.sample
  scripts/provisioning/templates/s3.config.tmpl.1-node
  scripts/provisioning/templates/s3.config.tmpl.1-node.sample
  scripts/provisioning/templates/s3.config.tmpl.3-node
  scripts/provisioning/templates/s3.config.tmpl.3-node.sample
  scripts/provisioning/templates/s3.init.tmpl.1-node
  scripts/provisioning/templates/s3.init.tmpl.1-node.sample
  scripts/provisioning/templates/s3.reset.tmpl.1-node
  scripts/provisioning/templates/s3.reset.tmpl.1-node.sample
  scripts/s3-support-bundles/s3_bundle_generate.sh
  scripts/swupdate/merge.py
  server/s3_auth_context.cc
  server/s3_cli_options.cc
  server/s3_option.cc
  st/clitests/auth_spec.py
  st/clitests/auth_spec_negative_and_fi.py
  startauth.sh
  system/s3server@.service
  system/s3startsystem.sh
  ut/s3_option_test.cc
Labels: cla-signed, HelloWorld

#1223 EOS-23476 [F-99A] k8s ENABLER: s3server: changes in entrypoint script
  scripts/provisioning/s3_start
  server/s3_cli_options.cc
  server/s3_cli_options.h
  server/s3_daemonize_server.cc
  server/s3_daemonize_server.h
  server/s3_option.cc
  server/s3_option.h
  server/s3server.cc
  system/s3server@.service
  system/s3startsystem.sh
Labels: cla-signed, Maverick

#1238 [K8S] EOS-24813:S3: workaround step for bgdelete producer
  s3cortxutils/s3msgbus/s3msgbus/cortx_s3_msgbus.py
Labels: cla-signed, HelloWorld

#1242 [F-8E] S3 HA: fixes and improvements for handling requests during shutdown
  s3config-test.yaml
  s3config.release.yaml.sample
  s3config.yaml.sample
  server/s3_account_delete_metadata_action.cc
  server/s3_common_utilities.cc
  server/s3_copy_object_action.cc
  server/s3_delete_bucket_policy_action.cc
  server/s3_delete_bucket_tagging_action.cc
  server/s3_delete_object_tagging_action.cc
  server/s3_get_bucket_acl_action.cc
  server/s3_get_bucket_action.cc
  server/s3_get_bucket_action_v2.cc
  server/s3_get_bucket_location_action.cc
  server/s3_get_bucket_policy_action.cc
  server/s3_get_bucket_tagging_action.cc
  server/s3_get_multipart_bucket_action.cc
  server/s3_get_multipart_part_action.cc
  server/s3_get_object_acl_action.cc
  server/s3_get_object_action.cc
  server/s3_get_object_tagging_action.cc
  server/s3_get_service_action.cc
  server/s3_head_bucket_action.cc
  server/s3_head_object_action.cc
  server/s3_head_service_action.cc
  server/s3_option.cc
  server/s3_option.h
  server/s3_post_multipartobject_action.cc
  server/s3_put_bucket_acl_action.cc
  server/s3_put_bucket_action.cc
  server/s3_put_bucket_policy_action.cc
  server/s3_put_bucket_tagging_action.cc
  server/s3_put_chunk_upload_object_action.cc
  server/s3_put_multiobject_action.cc
  server/s3_put_object_acl_action.cc
  server/s3_put_object_action.cc
  server/s3_put_object_tagging_action.cc
  server/s3server.cc
  ut/s3_copy_object_action_test.cc
  ut/s3_get_bucket_acl_action_test.cc
  ut/s3_get_bucket_location_action_test.cc
  ut/s3_head_object_action_test.cc
  ut/s3_put_bucket_acl_action_test.cc
  ut/s3_put_chunk_upload_object_action_test.cc
  ut/s3_put_object_action_test.cc
Labels: cla-signed, Maverick

#1248 K8s changes to adhere with latest function.
  scripts/provisioning/configcmd.py
  scripts/provisioning/setupcmd.py
Labels: cla-signed

#1247 EOS-22342: Fix redirection in haproxy entry point script
  scripts/provisioning/s3_start
Labels: cla-signed, Maverick

#1250 Auth server startup now takes config base path as 1st arg
  scripts/provisioning/s3_start
Labels: cla-signed, Maverick

#1249 [F-23B] enable DI with latest Main branch
  s3config-test.yaml
  s3config.release.yaml.sample
  s3config.yaml.sample
Labels: cla-signed

#1252 EOS-24038: Generate log directories based on machine id for all modules
  scripts/provisioning/configcmd.py
  scripts/provisioning/resetcmd.py
  scripts/provisioning/s3_prov_config.yaml
  scripts/provisioning/setupcmd.py
  scripts/provisioning/templates/s3.config.tmpl.1-node
  scripts/provisioning/templates/s3.config.tmpl.1-node.sample
  scripts/provisioning/templates/s3.config.tmpl.3-node
  scripts/provisioning/templates/s3.config.tmpl.3-node.sample
  scripts/provisioning/templates/s3.init.tmpl.1-node
  scripts/provisioning/templates/s3.init.tmpl.1-node.sample
  system/s3startsystem.sh
Labels: cla-signed, HelloWorld

#1251 [EOS-24037] Config changes on k8s branch
  s3config-test.yaml
  s3config.release.yaml.sample
  s3config.yaml.sample
  scripts/provisioning/configcmd.py
  scripts/provisioning/initcmd.py
  scripts/provisioning/s3_haproxy_config.py
  scripts/provisioning/s3_prov_config.yaml
  scripts/provisioning/s3_setup
  scripts/provisioning/setupcmd.py
  scripts/provisioning/templates/s3.cleanup.tmpl.1-node
  scripts/provisioning/templates/s3.cleanup.tmpl.1-node.sample
  scripts/provisioning/templates/s3.config.tmpl.1-node
  scripts/provisioning/templates/s3.config.tmpl.1-node.sample
  scripts/provisioning/templates/s3.config.tmpl.3-node
  scripts/provisioning/templates/s3.config.tmpl.3-node.sample
  scripts/provisioning/templates/s3.init.tmpl.1-node
  scripts/provisioning/templates/s3.init.tmpl.1-node.sample
  scripts/provisioning/templates/s3.reset.tmpl.1-node
  scripts/provisioning/templates/s3.reset.tmpl.1-node.sample
  system/s3startsystem.sh
Labels: cla-signed, HelloWorld

#1255 [EOS-24037] : [K8s] Generate log directories based on container id for s3 component (P2)
  scripts/provisioning/cleanupcmd.py
  scripts/provisioning/configcmd.py
  scripts/provisioning/resetcmd.py
  scripts/provisioning/s3_haproxy_config.py
  scripts/provisioning/s3_setup
  scripts/provisioning/setupcmd.py
Labels: cla-signed

#1260 Flag rename changes
  scripts/provisioning/configcmd.py
  scripts/provisioning/s3_setup
Labels: cla-signed

#1265 Updating config file to latest
  scripts/provisioning/templates/s3.config.tmpl.1-node
  scripts/provisioning/templates/s3.config.tmpl.1-node.sample
  scripts/provisioning/templates/s3.config.tmpl.3-node
  scripts/provisioning/templates/s3.config.tmpl.3-node.sample
Labels: cla-signed

#1266 EOS-24042: add convertor functions for bg delete port, and auth host and ports
  scripts/provisioning/configcmd.py
Labels: cla-signed

#1267 New config changes
  scripts/provisioning/templates/s3.config.tmpl.1-node
  scripts/provisioning/templates/s3.config.tmpl.1-node.sample
  scripts/provisioning/templates/s3.config.tmpl.3-node
  scripts/provisioning/templates/s3.config.tmpl.3-node.sample
Labels: cla-signed

#1268 [EOS-24361] : Mini prov Fix
  scripts/provisioning/configcmd.py
  scripts/provisioning/setupcmd.py
  scripts/provisioning/templates/s3.config.tmpl.1-node
  scripts/provisioning/templates/s3.config.tmpl.1-node.sample
  scripts/provisioning/templates/s3.config.tmpl.3-node
  scripts/provisioning/templates/s3.config.tmpl.3-node.sample
Labels: cla-signed

#1269 EOS-24042: confstore: more fixes and address review comments
  scripts/provisioning/configcmd.py
Labels: cla-signed

#1270 Mini prov fix.
  scripts/provisioning/configcmd.py
  scripts/provisioning/templates/s3.config.tmpl.1-node
  scripts/provisioning/templates/s3.config.tmpl.1-node.sample
  scripts/provisioning/templates/s3.config.tmpl.3-node
  scripts/provisioning/templates/s3.config.tmpl.3-node.sample
Labels: cla-signed

#1272 Init template file changes
  scripts/provisioning/configcmd.py
  scripts/provisioning/s3_haproxy_config.py
  scripts/provisioning/templates/s3.config.tmpl.1-node
  scripts/provisioning/templates/s3.config.tmpl.1-node.sample
  scripts/provisioning/templates/s3.config.tmpl.3-node
  scripts/provisioning/templates/s3.config.tmpl.3-node.sample
  scripts/provisioning/templates/s3.init.tmpl.1-node
  scripts/provisioning/templates/s3.init.tmpl.1-node.sample
Labels: cla-signed

#1262 EOS-24042:S3: Mapping of new provisioner confstore keys to s3 confstore keys for K8S
  scripts/provisioning/configcmd.py
  scripts/provisioning/s3_haproxy_config.py
  scripts/provisioning/s3_prov_config.yaml
  scripts/provisioning/setupcmd.py
  scripts/provisioning/templates/s3.config.tmpl.1-node
  scripts/provisioning/templates/s3.config.tmpl.1-node.sample
  scripts/provisioning/templates/s3.config.tmpl.3-node
  scripts/provisioning/templates/s3.config.tmpl.3-node.sample
  scripts/provisioning/templates/s3.init.tmpl.1-node
  scripts/provisioning/templates/s3.init.tmpl.1-node.sample
Labels: cla-signed

#1257 EOS-24853 [Centos-7.9] : Failures observed for aws s3 requests sent t…
  scripts/provisioning/configcmd.py
Labels: cla-signed

#1274 fixes for mini-prov
  scripts/provisioning/configcmd.py
  scripts/provisioning/s3_prov_config.yaml
  scripts/provisioning/templates/s3.config.tmpl.1-node
  scripts/provisioning/templates/s3.config.tmpl.1-node.sample
  scripts/provisioning/templates/s3.config.tmpl.3-node
  scripts/provisioning/templates/s3.config.tmpl.3-node.sample
  scripts/provisioning/templates/s3.init.tmpl.1-node
  scripts/provisioning/templates/s3.init.tmpl.1-node.sample
Labels: cla-signed

#1261 EOS-24655 - Kubernetes haproxy micro-provisioner code changes.
  installhelper.sh
  rpms/s3/s3rpm.spec
  scripts/provisioning/s3_haproxy_config.py
  scripts/provisioning/s3_start
  scripts/provisioning/starthaproxy.sh
Labels: cla-signed, Maverick

#1276 Changes related with new conf keys
  scripts/provisioning/configcmd.py
  scripts/provisioning/templates/s3.cleanup.tmpl.1-node
  scripts/provisioning/templates/s3.cleanup.tmpl.1-node.sample
  scripts/provisioning/templates/s3.config.tmpl.1-node
  scripts/provisioning/templates/s3.config.tmpl.1-node.sample
  scripts/provisioning/templates/s3.config.tmpl.3-node
  scripts/provisioning/templates/s3.config.tmpl.3-node.sample
  scripts/provisioning/templates/s3.init.tmpl.1-node
  scripts/provisioning/templates/s3.init.tmpl.1-node.sample
  scripts/provisioning/templates/s3.reset.tmpl.1-node
  scripts/provisioning/templates/s3.reset.tmpl.1-node.sample
Labels: cla-signed

#1278 Open ldap mp changes
  ansible/openldap.yml
  auth/server/s3authserver.service
  installhelper.sh
  rpms/s3/s3rpm.spec
  scripts/enc_ldap_passwd_in_cfg.sh
  scripts/env/dev/init.sh
  scripts/env/release/init.sh
  scripts/ldap/cn={2}s3user.ldif
  scripts/ldap/iam-admin-access.ldif
  scripts/ldap/readme
  scripts/ldap/s3_setup_ldap.sh
  scripts/ldap/setup_ldap.sh
  scripts/ldap/update_ldap_schema.sh
  scripts/provisioning/clean_openldap.sh
  scripts/provisioning/cleanupcmd.py
  scripts/provisioning/configcmd.py
  scripts/provisioning/s3_setup
  scripts/provisioning/s3setup_prereqs.json
  scripts/provisioning/setupcmd.py
  scripts/provisioning/templates/s3.cleanup.tmpl.1-node
  scripts/provisioning/templates/s3.cleanup.tmpl.1-node.sample
  scripts/provisioning/templates/s3.config.tmpl.1-node
  scripts/provisioning/templates/s3.config.tmpl.1-node.sample
  scripts/provisioning/templates/s3.config.tmpl.3-node
  scripts/provisioning/templates/s3.config.tmpl.3-node.sample
  scripts/provisioning/templates/s3.init.tmpl.1-node
  scripts/provisioning/templates/s3.init.tmpl.1-node.sample
  scripts/provisioning/templates/s3.reset.tmpl.1-node
  scripts/provisioning/templates/s3.reset.tmpl.1-node.sample
Labels: cla-signed

#1280 Added setup type to prepare and post install phase.
  scripts/provisioning/templates/s3.post_install.tmpl.1-node
  scripts/provisioning/templates/s3.post_install.tmpl.1-node.sample
  scripts/provisioning/templates/s3.prepare.tmpl.1-node
  scripts/provisioning/templates/s3.prepare.tmpl.1-node.sample
  scripts/provisioning/templates/s3.test.tmpl.1-node
  scripts/provisioning/templates/s3.test.tmpl.1-node.sample
Labels: cla-signed

#1281 Added Setup type as K8 to all phases.
  scripts/provisioning/templates/s3.post_install.tmpl.1-node
  scripts/provisioning/templates/s3.post_install.tmpl.1-node.sample
  scripts/provisioning/templates/s3.prepare.tmpl.1-node
  scripts/provisioning/templates/s3.prepare.tmpl.1-node.sample
  scripts/provisioning/templates/s3.test.tmpl.1-node
  scripts/provisioning/templates/s3.test.tmpl.1-node.sample
Labels: cla-signed

#1282 EOS23401- Handling for --service parameter in s3 provisioning
  scripts/provisioning/cleanupcmd.py
  scripts/provisioning/configcmd.py
  scripts/provisioning/initcmd.py
  scripts/provisioning/postinstallcmd.py
  scripts/provisioning/postupgradecmd.py
  scripts/provisioning/preparecmd.py
  scripts/provisioning/preupgradecmd.py
  scripts/provisioning/resetcmd.py
  scripts/provisioning/s3_setup
  scripts/provisioning/setupcmd.py
Labels: cla-signed

#1287 Services Fix
  scripts/provisioning/preupgradecmd.py
  scripts/provisioning/setupcmd.py
Labels: cla-signed

#1277 HAproxy port numbers should be read from confstore.
  scripts/provisioning/s3_haproxy_config.py
  scripts/provisioning/templates/s3.config.tmpl.1-node
  scripts/provisioning/templates/s3.config.tmpl.1-node.sample
  scripts/provisioning/templates/s3.config.tmpl.3-node
  scripts/provisioning/templates/s3.config.tmpl.3-node.sample
  scripts/provisioning/templates/s3.init.tmpl.1-node
  scripts/provisioning/templates/s3.init.tmpl.1-node.sample
Labels: cla-signed

#1288 Slapd password hash changes
  scripts/ldap/s3_setup_ldap.sh
Labels: cla-signed

#1292 EOS-24974: Fix auth base config path in startauth.sh argument
  auth/server/s3authserver.service
  scripts/provisioning/s3_start
Labels: cla-signed, Maverick

#1294 Remove hardcoded ldaphost string from ldapaccountaction class
  scripts/ldap/ldapaccountaction.py
  scripts/provisioning/configcmd.py
Labels: cla-signed

#1289 Perform s3 ldap config if services None or contains openldap
  scripts/ldap/s3_setup_ldap.sh
  scripts/provisioning/configcmd.py
  scripts/provisioning/s3_setup
Labels: cla-signed, Maverick

#1297 EOS-24939: Terminate S3 server if motr_init got hung
  server/s3server.cc
Labels: Maverick

#1299 Revert "enable DI with latest Main branch (#1249)"
  s3config-test.yaml
  s3config.release.yaml.sample
  s3config.yaml.sample
Labels: cla-signed

#1303 HAproxy should read config path from confstore.
  scripts/provisioning/s3_haproxy_config.py
  scripts/provisioning/s3_prov_config.yaml
  scripts/provisioning/setupcmd.py
Labels: cla-signed

#1306 Sagregated log dir for producer/consumer
  s3backgrounddelete/s3backgrounddelete/config/s3_background_delete_config.yaml.sample
  s3backgrounddelete/s3backgrounddelete/cortx_s3_config.py
  s3backgrounddelete/s3backgrounddelete/object_recovery_processor.py
  s3backgrounddelete/s3backgrounddelete/object_recovery_scheduler.py
  scripts/provisioning/configcmd.py
  scripts/provisioning/s3_haproxy_config.py
  scripts/provisioning/s3_prov_config.yaml
Labels: cla-signed

#1273 [EOS-22168] Multipart object overwrite with Simple object (bgdelete handling)
  s3backgrounddelete/s3backgrounddelete/object_recovery_validator.py
  server/s3_post_complete_action.cc
  server/s3_put_object_action.cc
  server/s3_put_object_action.h
Labels: cla-signed, HelloWorld

#1307 K8: Remove chkconfig call from openldap setup script
  scripts/ldap/s3_setup_ldap.sh
Labels: cla-signed

#1311 EOS-24974: Use machine-id in log path for haproxy log file
  scripts/provisioning/configcmd.py
  scripts/provisioning/s3_start
  scripts/provisioning/starthaproxy.sh
Labels: cla-signed

#1309 [EOS-25020] Fix for logger race
  s3backgrounddelete/s3backgrounddelete/object_recovery_processor.py
  s3backgrounddelete/s3backgrounddelete/object_recovery_scheduler.py
  scripts/provisioning/s3_setup
  scripts/provisioning/s3_start
Labels: cla-signed

#1312 Changes to template files to accomodate array entries in new format
  s3cortxutils/s3confstore/s3confstore/cortx_s3_confstore.py
  scripts/provisioning/configcmd.py
  scripts/provisioning/setupcmd.py
  scripts/provisioning/templates/s3.config.tmpl.1-node
  scripts/provisioning/templates/s3.config.tmpl.1-node.sample
  scripts/provisioning/templates/s3.config.tmpl.3-node
  scripts/provisioning/templates/s3.config.tmpl.3-node.sample
  scripts/provisioning/templates/s3.init.tmpl.1-node
  scripts/provisioning/templates/s3.init.tmpl.1-node.sample
Labels: cla-signed

#1313 [MINI PROV] : Fixed deployment logger bug
  scripts/provisioning/s3_setup
  scripts/provisioning/templates/s3.cleanup.tmpl.1-node
  scripts/provisioning/templates/s3.cleanup.tmpl.1-node.sample
  scripts/provisioning/templates/s3.post_install.tmpl.1-node
  scripts/provisioning/templates/s3.post_install.tmpl.1-node.sample
  scripts/provisioning/templates/s3.prepare.tmpl.1-node
  scripts/provisioning/templates/s3.prepare.tmpl.1-node.sample
  scripts/provisioning/templates/s3.reset.tmpl.1-node
  scripts/provisioning/templates/s3.reset.tmpl.1-node.sample
  scripts/provisioning/templates/s3.test.tmpl.1-node
  scripts/provisioning/templates/s3.test.tmpl.1-node.sample
Labels: cla-signed

#1240 EOS-22175: S3 large object workload handling on VM
  mempool/s3_memory_pool.c
  patches/libevent-release-2.1.10-stable.patch
  s3config-test.yaml
  s3config.release.yaml.sample
  s3config.yaml.sample
  server/action_base.h
  server/evhtp_wrapper.cc
  server/evhtp_wrapper.h
  server/request_object.cc
  server/request_object.h
  server/s3_action_base.cc
  server/s3_action_base.h
  server/s3_evbuffer_wrapper.cc
  server/s3_fi_common.c
  server/s3_fi_common.h
  server/s3_get_object_action.cc
  server/s3_get_object_action.h
  server/s3_mem_pool_manager.cc
  server/s3_object_action_base.cc
  server/s3_object_action_base.h
  server/s3_option.cc
  server/s3_option.h
  server/s3_put_object_action.cc
  server/s3server.cc
  ut/mock_evhtp_wrapper.h
  ut/s3_server_tests.cc
  ut_death_tests/s3_server_tests.cc
Labels: cla-signed, Maverick

#1317 Changes to keys to align with confstore
  scripts/provisioning/configcmd.py
  scripts/provisioning/s3_prov_config.yaml
  scripts/provisioning/setupcmd.py
  scripts/provisioning/templates/s3.cleanup.tmpl.1-node
  scripts/provisioning/templates/s3.cleanup.tmpl.1-node.sample
  scripts/provisioning/templates/s3.config.tmpl.1-node
  scripts/provisioning/templates/s3.config.tmpl.1-node.sample
  scripts/provisioning/templates/s3.config.tmpl.3-node
  scripts/provisioning/templates/s3.config.tmpl.3-node.sample
  scripts/provisioning/templates/s3.init.tmpl.1-node
  scripts/provisioning/templates/s3.init.tmpl.1-node.sample
  scripts/provisioning/templates/s3.reset.tmpl.1-node
  scripts/provisioning/templates/s3.reset.tmpl.1-node.sample
Labels: cla-signed

#1314 Copy of the multipart uploaded object
  s3backgrounddelete/s3backgrounddelete/object_recovery_validator.py
  server/s3_addb_map_auto.c
  server/s3_common.h
  server/s3_copy_object_action.cc
  server/s3_copy_object_action.h
  server/s3_motr_reader.h
  server/s3_object_action_base.cc
  server/s3_object_data_copier.cc
  server/s3_object_data_copier.h
  server/s3_object_metadata.cc
  server/s3_object_metadata.h
  server/s3_put_object_action.cc
  server/s3_put_object_action_base.cc
  server/s3_put_object_action_base.h
  ut/s3_copy_object_action_test.cc
Labels: cla-signed

#1318 Update default endpoints in s3 config tmpl
  scripts/provisioning/templates/s3.config.tmpl.1-node
  scripts/provisioning/templates/s3.config.tmpl.1-node.sample
  scripts/provisioning/templates/s3.config.tmpl.3-node
  scripts/provisioning/templates/s3.config.tmpl.3-node.sample
  scripts/provisioning/templates/s3.init.tmpl.1-node
  scripts/provisioning/templates/s3.init.tmpl.1-node.sample
Labels: cla-signed

#1316 [ EOS-24340 ] : Loading more values for multipart extended index
  server/s3_post_complete_action.cc
  server/s3_post_complete_action.h
Labels: cla-signed

#1324 [K8 Bug] EOS-25051:S3: Increase motr init time from 15s -> 60s
  server/s3server.cc
Labels: cla-signed

#1327 Fixes for Provisioner
  scripts/provisioning/configcmd.py
  scripts/provisioning/s3_prov_config.yaml
  scripts/provisioning/setupcmd.py
  scripts/provisioning/templates/s3.cleanup.tmpl.1-node
  scripts/provisioning/templates/s3.cleanup.tmpl.1-node.sample
  scripts/provisioning/templates/s3.config.tmpl.1-node
  scripts/provisioning/templates/s3.config.tmpl.1-node.sample
  scripts/provisioning/templates/s3.config.tmpl.3-node
  scripts/provisioning/templates/s3.config.tmpl.3-node.sample
  scripts/provisioning/templates/s3.init.tmpl.1-node
  scripts/provisioning/templates/s3.init.tmpl.1-node.sample
  scripts/provisioning/templates/s3.reset.tmpl.1-node
  scripts/provisioning/templates/s3.reset.tmpl.1-node.sample
Labels: cla-signed
